# action.yml
name: 'Autotrain Digital Counter'
description: 'This action covers the entire process'
outputs:
  time: # id of output
    description: 'Models and reports'
runs:
  using: 'docker'
  image: 'd_scripts_effnet/Dockerfile'
