on: [workflow_dispatch]

jobs:
  manual_training_job:
    runs-on: ubuntu-latest
    name: Manually triggered training job
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: run ./action.yml
        uses: ./ # Uses an action in the root directory
        id: hello
      - name: push changes to remote
        run: |
           git config --global user.name "github-actions"
           git config --global user.email "github-actions@github.com"
           git add ./ 
           git add ./a_output_actual/
           git add ./b_output_historic/
           git commit -m "manual run"
           git push
